spring.application.name=zero-trust-access

spring.datasource.url=jdbc:postgresql://localhost:5434/zero_trust
spring.datasource.username=zt_admin
spring.datasource.password=change_me_locally
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8083